# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
