# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0002_auto_20190325_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
